microserviceName: "identity"

image:
  repository: iga1playeconomy.azurecr.io/play.identity
  tag: 1.0.10

envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
  IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
  IdentityServerSettings__Clients__0__RedirectUris__0: https://iga1dotapprentice.eastus.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: https://iga1dotapprentice.eastus.cloudapp.azure.com/authentication/logout-callback

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates

volumes:
  - name: certificate-volume
    secret:
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

service:
  type: ClusterIP
  port: 80

certificate:
  secretName: signing-cert
  hostname: iga1dotapprentice.eastus.cloudapp.azure.com
